#' @title MDX VBA Functions (auto-generated)
#' @description Auto-generated MDX function wrappers for vba.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX Abs function
#'
#' Returns a value of the same type that is passed to it specifying the absolute value of a number.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_abs <- function(number) {
  paste0("Abs(", number, ")")
}

#' MDX Asc function
#'
#' Returns an Integer representing the character code corresponding to the first letter in a string.
#'
#' @param string A String expression.
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_asc <- function(string) {
  paste0("Asc(", string, ")")
}

#' MDX Atn function
#'
#' Returns a Double specifying the arctangent of a number.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_atn <- function(number) {
  paste0("Atn(", number, ")")
}

#' MDX CBool function
#'
#' Returns an expression that has been converted to a Variant of subtype Boolean.
#'
#' @param expression A Value expression.
#' @return MDX string returning Logical Expression.
#' @family vba
#' @export
mdx_cbool <- function(expression) {
  paste0("CBool(", expression, ")")
}

#' MDX CByte function
#'
#' Returns an expression that has been converted to a Variant of subtype Boolean.
#'
#' @param expression A Value expression.
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_cbyte <- function(expression) {
  paste0("CByte(", expression, ")")
}

#' MDX CDate function
#'
#' Returns an expression that has been converted to a Variant of subtype
#'
#' @param expression A Value expression.
#' @return MDX string returning DateTime.
#' @family vba
#' @export
mdx_cdate <- function(expression) {
  paste0("CDate(", expression, ")")
}

#' MDX CDbl function
#'
#' Returns an expression that has been converted to a Variant of subtype Double.
#'
#' @param expression A Value expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_cdbl <- function(expression) {
  paste0("CDbl(", expression, ")")
}

#' MDX Chr function
#'
#' Returns an Integer representing the character code corresponding to the first letter in a string.
#'
#' @param charcode A Integer expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_chr <- function(charcode) {
  paste0("Chr(", charcode, ")")
}

#' MDX ChrB function
#'
#' Returns an Integer representing the character code corresponding to the first letter in a string.
#'
#' @param charcode A Integer expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_chr_b <- function(charcode) {
  paste0("ChrB(", charcode, ")")
}

#' MDX CInt function
#'
#' Returns an expression that has been converted to a Variant of subtype Integer.
#'
#' @param expression A Numeric Expression expression.
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_cint <- function(expression) {
  paste0("CInt(", expression, ")")
}

#' MDX Cos function
#'
#' Returns a Double specifying the cosine of an angle.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_cos <- function(number) {
  paste0("Cos(", number, ")")
}

#' MDX Date function
#'
#' Returns a Variant (Date) containing the current system date.
#'
#' @return MDX string returning DateTime.
#' @family vba
#' @export
mdx_date <- function() {
  paste0("Date()")
}

#' MDX DateAdd function
#'
#' Returns a Variant (Date) containing a date to which a specified time interval has been added.
#'
#' @param interval_name A String expression.
#' @param number A Numeric Expression expression.
#' @param date A DateTime expression.
#' @return MDX string returning DateTime.
#' @family vba
#' @export
mdx_date_add <- function(interval_name, number, date) {
  paste0("DateAdd(", interval_name, ", ", number, ", ", date, ")")
}

#' MDX DateDiff function
#'
#' Returns a Variant (Long) specifying the number of time intervals between two specified dates.
#'
#' @param interval_name A String expression.
#' @param date1 A DateTime expression.
#' @param date2 A DateTime expression.
#' @param first_day_of_week A Integer expression (optional).
#' @param first_week_of_year A Integer expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_date_diff <- function(interval_name, date1, date2, first_day_of_week = NULL, first_week_of_year = NULL) {
  args <- paste0(interval_name, ", ", date1, ", ", date2)
  if (!is.null(first_day_of_week)) args <- paste0(args, ", ", first_day_of_week)
  if (!is.null(first_week_of_year)) args <- paste0(args, ", ", first_week_of_year)
  paste0("DateDiff(", args, ")")
}

#' MDX DatePart function
#'
#' Returns a Variant (Integer) containing the specified part of a given date.
#'
#' @param interval_name A String expression.
#' @param date1 A DateTime expression.
#' @param date2 A DateTime expression.
#' @param first_day_of_week A Integer expression (optional).
#' @param first_week_of_year A Integer expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_date_part <- function(interval_name, date1, date2, first_day_of_week = NULL, first_week_of_year = NULL) {
  args <- paste0(interval_name, ", ", date1, ", ", date2)
  if (!is.null(first_day_of_week)) args <- paste0(args, ", ", first_day_of_week)
  if (!is.null(first_week_of_year)) args <- paste0(args, ", ", first_week_of_year)
  paste0("DatePart(", args, ")")
}

#' MDX DateSerial function
#'
#' Returns a Variant (Date) for a specified year, month, and day.
#'
#' @param year A Integer expression.
#' @param month A Integer expression.
#' @param day A Integer expression.
#' @return MDX string returning DateTime.
#' @family vba
#' @export
mdx_date_serial <- function(year, month, day) {
  paste0("DateSerial(", year, ", ", month, ", ", day, ")")
}

#' MDX DateValue function
#'
#' Returns a Variant (Date) for a specified year, month, and day.
#'
#' @param date A DateTime expression.
#' @return MDX string returning DateTime.
#' @family vba
#' @export
mdx_date_value <- function(date) {
  paste0("DateValue(", date, ")")
}

#' MDX Day function
#'
#' Returns a Variant (Integer) specifying a whole number between 1 and 31, inclusive, representing the day of the month.
#'
#' @param date A DateTime expression.
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_day <- function(date) {
  paste0("Day(", date, ")")
}

#' MDX DDB function
#'
#' Returns a Double specifying the depreciation of an asset for a specific time period using the double-declining balance method or some other method you specify.
#'
#' @param cost A Numeric Expression expression.
#' @param salvage A Numeric Expression expression.
#' @param life A Numeric Expression expression.
#' @param period A Numeric Expression expression.
#' @param factor A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_ddb <- function(cost, salvage, life, period, factor = NULL) {
  args <- paste0(cost, ", ", salvage, ", ", life, ", ", period)
  if (!is.null(factor)) args <- paste0(args, ", ", factor)
  paste0("DDB(", args, ")")
}

#' MDX Exp function
#'
#' Returns a Double specifying e (the base of natural logarithms) raised to a power.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_exp <- function(number) {
  paste0("Exp(", number, ")")
}

#' MDX Fix function
#'
#' Returns an expression that has been converted to a Variant of subtype Integer.
#'
#' @param expression A Value expression.
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_fix <- function(expression) {
  paste0("Fix(", expression, ")")
}

#' MDX FormatCurrency function
#'
#' Returns an expression formatted as a currency value using the currency symbol defined in the system control panel.
#'
#' @param expression A Value expression.
#' @param num_digits_after_decimal A Integer expression (optional).
#' @param include_leading_digit A Integer expression (optional).
#' @param use_parens_for_negative_numbers A Integer expression (optional).
#' @param group_digits A Integer expression (optional).
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_format_currency <- function(expression, num_digits_after_decimal = NULL, include_leading_digit = NULL, use_parens_for_negative_numbers = NULL, group_digits = NULL) {
  args <- paste0(expression)
  if (!is.null(num_digits_after_decimal)) args <- paste0(args, ", ", num_digits_after_decimal)
  if (!is.null(include_leading_digit)) args <- paste0(args, ", ", include_leading_digit)
  if (!is.null(use_parens_for_negative_numbers)) args <- paste0(args, ", ", use_parens_for_negative_numbers)
  if (!is.null(group_digits)) args <- paste0(args, ", ", group_digits)
  paste0("FormatCurrency(", args, ")")
}

#' MDX FormatDateTime function
#'
#' Returns an expression formatted as a date or time.
#'
#' @param date A DateTime expression.
#' @param named_format A Integer expression (optional).
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_format_date_time <- function(date, named_format = NULL) {
  args <- paste0(date)
  if (!is.null(named_format)) args <- paste0(args, ", ", named_format)
  paste0("FormatDateTime(", args, ")")
}

#' MDX FormatNumber function
#'
#' Returns an expression formatted as a number.
#'
#' @param expression A Value expression.
#' @param digits_after_decimal A Integer expression (optional).
#' @param include_leading_digit A Integer expression (optional).
#' @param use_parens_for_negative_numbers A Integer expression (optional).
#' @param group_digits A Integer expression (optional).
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_format_number <- function(expression, digits_after_decimal = NULL, include_leading_digit = NULL, use_parens_for_negative_numbers = NULL, group_digits = NULL) {
  args <- paste0(expression)
  if (!is.null(digits_after_decimal)) args <- paste0(args, ", ", digits_after_decimal)
  if (!is.null(include_leading_digit)) args <- paste0(args, ", ", include_leading_digit)
  if (!is.null(use_parens_for_negative_numbers)) args <- paste0(args, ", ", use_parens_for_negative_numbers)
  if (!is.null(group_digits)) args <- paste0(args, ", ", group_digits)
  paste0("FormatNumber(", args, ")")
}

#' MDX FormatPercent function
#'
#' Returns an expression formatted as a percentage (multipled by 100) with a trailing % character.
#'
#' @param expression A Value expression.
#' @param digits_after_decimal A Integer expression (optional).
#' @param include_leading_digit A Integer expression (optional).
#' @param use_parens_for_negative_numbers A Integer expression (optional).
#' @param group_digits A Integer expression (optional).
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_format_percent <- function(expression, digits_after_decimal = NULL, include_leading_digit = NULL, use_parens_for_negative_numbers = NULL, group_digits = NULL) {
  args <- paste0(expression)
  if (!is.null(digits_after_decimal)) args <- paste0(args, ", ", digits_after_decimal)
  if (!is.null(include_leading_digit)) args <- paste0(args, ", ", include_leading_digit)
  if (!is.null(use_parens_for_negative_numbers)) args <- paste0(args, ", ", use_parens_for_negative_numbers)
  if (!is.null(group_digits)) args <- paste0(args, ", ", group_digits)
  paste0("FormatPercent(", args, ")")
}

#' MDX FV function
#'
#' Returns a Double specifying the future value of an annuity based on periodic, fixed payments and a fixed interest rate.
#'
#' @param rate A Numeric Expression expression.
#' @param nper A Numeric Expression expression.
#' @param pmt A Numeric Expression expression.
#' @param pv A Numeric Expression expression (optional).
#' @param type A Logical Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_fv <- function(rate, nper, pmt, pv = NULL, type = NULL) {
  args <- paste0(rate, ", ", nper, ", ", pmt)
  if (!is.null(pv)) args <- paste0(args, ", ", pv)
  if (!is.null(type)) args <- paste0(args, ", ", type)
  paste0("FV(", args, ")")
}

#' MDX Hex function
#'
#' Returns a String representing the hexadecimal value of a number.
#'
#' @param number A Value expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_hex <- function(number) {
  paste0("Hex(", number, ")")
}

#' MDX Hour function
#'
#' Returns a Variant (Integer) specifying a whole number between 0 and 23, inclusive, representing the hour of the day.
#'
#' @param date A DateTime expression.
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_hour <- function(date) {
  paste0("Hour(", date, ")")
}

#' MDX InStr function
#'
#' Returns a Variant (Long) specifying the position of the first occurrence of one string within another.
#'
#' @param string_check A String expression.
#' @param string_match A String expression.
#' @param string_match_3 A String expression (optional).
#' @param compare A Integer expression (optional).
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_in_str <- function(string_check, string_match, string_match_3 = NULL, compare = NULL) {
  args <- paste0(string_check, ", ", string_match)
  if (!is.null(string_match_3)) args <- paste0(args, ", ", string_match_3)
  if (!is.null(compare)) args <- paste0(args, ", ", compare)
  paste0("InStr(", args, ")")
}

#' MDX InStrRev function
#'
#' Returns the position of an occurrence of one string within another, from the end of string.
#'
#' @param string_check A String expression.
#' @param string_match A String expression.
#' @param start A Integer expression (optional).
#' @param compare A Integer expression (optional).
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_in_str_rev <- function(string_check, string_match, start = NULL, compare = NULL) {
  args <- paste0(string_check, ", ", string_match)
  if (!is.null(start)) args <- paste0(args, ", ", start)
  if (!is.null(compare)) args <- paste0(args, ", ", compare)
  paste0("InStrRev(", args, ")")
}

#' MDX Int function
#'
#' Returns the integer portion of a number. If negative, returns the negative number less than or equal to the number.
#'
#' @param expression A Value expression.
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_int <- function(expression) {
  paste0("Int(", expression, ")")
}

#' MDX IPmt function
#'
#' Returns a Double specifying the interest payment for a given period of an annuity based on periodic, fixed payments and a fixed interest rate.
#'
#' @param rate A Numeric Expression expression.
#' @param per A Numeric Expression expression.
#' @param nper A Numeric Expression expression.
#' @param pv A Numeric Expression expression.
#' @param fv A Numeric Expression expression (optional).
#' @param due A Logical Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_ipmt <- function(rate, per, nper, pv, fv = NULL, due = NULL) {
  args <- paste0(rate, ", ", per, ", ", nper, ", ", pv)
  if (!is.null(fv)) args <- paste0(args, ", ", fv)
  if (!is.null(due)) args <- paste0(args, ", ", due)
  paste0("IPmt(", args, ")")
}

#' MDX IRR function
#'
#' Returns a Double specifying the internal rate of return for a series of periodic cash flows (payments and receipts).
#'
#' @param value_array A Array expression.
#' @param guess A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_irr <- function(value_array, guess = NULL) {
  args <- paste0(value_array)
  if (!is.null(guess)) args <- paste0(args, ", ", guess)
  paste0("IRR(", args, ")")
}

#' MDX IsArray function
#'
#' Returns a Boolean value indicating whether a variable is an array.
#'
#' @param var_name A Value expression.
#' @return MDX string returning Logical Expression.
#' @family vba
#' @export
mdx_is_array <- function(var_name) {
  paste0("IsArray(", var_name, ")")
}

#' MDX IsDate function
#'
#' Returns a Boolean value indicating whether an expression can be converted to a date.
#'
#' @param expression A Value expression.
#' @return MDX string returning Logical Expression.
#' @family vba
#' @export
mdx_is_date <- function(expression) {
  paste0("IsDate(", expression, ")")
}

#' MDX IsError function
#'
#' Returns a Boolean value indicating whether an expression is an error value.
#'
#' @param var_name A Value expression.
#' @return MDX string returning Logical Expression.
#' @family vba
#' @export
mdx_is_error <- function(var_name) {
  paste0("IsError(", var_name, ")")
}

#' MDX IsMissing function
#'
#' Returns a Boolean value indicating whether an optional Variant argument has been passed to a procedure.
#'
#' @param var_name A Value expression.
#' @return MDX string returning Logical Expression.
#' @family vba
#' @export
mdx_is_missing <- function(var_name) {
  paste0("IsMissing(", var_name, ")")
}

#' MDX IsNumeric function
#'
#' Returns a Boolean value indicating whether an expression can be evaluated as a number.
#'
#' @param var_name A Value expression.
#' @return MDX string returning Logical Expression.
#' @family vba
#' @export
mdx_is_numeric <- function(var_name) {
  paste0("IsNumeric(", var_name, ")")
}

#' MDX IsObject function
#'
#' Returns a Boolean value indicating whether an identifier represents an object variable.
#'
#' @param var_name A Value expression.
#' @return MDX string returning Logical Expression.
#' @family vba
#' @export
mdx_is_object <- function(var_name) {
  paste0("IsObject(", var_name, ")")
}

#' MDX Left function
#'
#' Returns a specified number of characters from the left side of a string.
#'
#' @param string A String expression.
#' @param length A Integer expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_left <- function(string, length) {
  paste0("Left(", string, ", ", length, ")")
}

#' MDX Log function
#'
#' Returns a Double specifying the natural logarithm of a number.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_log <- function(number) {
  paste0("Log(", number, ")")
}

#' MDX LTrim function
#'
#' Returns a Variant (String) containing a copy of a specified string without leading spaces.
#'
#' @param string A String expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_ltrim <- function(string) {
  paste0("LTrim(", string, ")")
}

#' MDX Mid function
#'
#' Returns a specified number of characters from a string.
#'
#' @param value A String expression.
#' @param begin_index A Integer expression.
#' @param length A Integer expression (optional).
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_mid <- function(value, begin_index, length = NULL) {
  args <- paste0(value, ", ", begin_index)
  if (!is.null(length)) args <- paste0(args, ", ", length)
  paste0("Mid(", args, ")")
}

#' MDX Minute function
#'
#' Returns a Variant (Integer) specifying a whole number between 0 and 59, inclusive, representing the minute of the hour.
#'
#' @param date A DateTime expression.
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_minute <- function(date) {
  paste0("Minute(", date, ")")
}

#' MDX MIRR function
#'
#' Returns a Double specifying the modified internal rate of return for a series of periodic cash flows (payments and receipts).
#'
#' @param value_array A Array expression.
#' @param finance_rate A Numeric Expression expression.
#' @param reinvest_rate A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_mirr <- function(value_array, finance_rate, reinvest_rate) {
  paste0("MIRR(", value_array, ", ", finance_rate, ", ", reinvest_rate, ")")
}

#' MDX Month function
#'
#' Returns a Variant (Integer) specifying a whole number between 1 and " + "12, inclusive, representing the month of the year.
#'
#' @param date A DateTime expression.
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_month <- function(date) {
  paste0("Month(", date, ")")
}

#' MDX MonthName function
#'
#' Returns a string indicating the specified month.
#'
#' @param month A Integer expression.
#' @param abbreviate A Logical Expression expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_month_name <- function(month, abbreviate) {
  paste0("MonthName(", month, ", ", abbreviate, ")")
}

#' MDX Now function
#'
#' Returns a Variant (Date) specifying the current date and time according your computer's system date and time.
#'
#' @return MDX string returning DateTime.
#' @family vba
#' @export
mdx_now <- function() {
  paste0("Now()")
}

#' MDX NPer function
#'
#' Returns a Double specifying the number of periods for an annuity based on periodic, fixed payments and a fixed interest rate.
#'
#' @param rate A Numeric Expression expression.
#' @param pmt A Numeric Expression expression.
#' @param pv A Numeric Expression expression.
#' @param fv A Numeric Expression expression.
#' @param due A Logical Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_nper <- function(rate, pmt, pv, fv, due) {
  paste0("NPer(", rate, ", ", pmt, ", ", pv, ", ", fv, ", ", due, ")")
}

#' MDX NPV function
#'
#' Returns a Double specifying the net present value of an investment based on a series of periodic cash flows (payments and receipts) and a discount rate.
#'
#' @param r A Numeric Expression expression.
#' @param cfs A Array expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_npv <- function(r, cfs) {
  paste0("NPV(", r, ", ", cfs, ")")
}

#' MDX Oct function
#'
#' Returns a Variant (String) representing the octal value of a number.
#'
#' @param number A Value expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_oct <- function(number) {
  paste0("Oct(", number, ")")
}

#' MDX Pmt function
#'
#' Returns a Double specifying the payment for an annuity based on periodic, fixed payments and a fixed interest rate.
#'
#' @param rate A Numeric Expression expression.
#' @param nper A Numeric Expression expression.
#' @param pv A Numeric Expression expression.
#' @param fv A Numeric Expression expression.
#' @param due A Logical Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_pmt <- function(rate, nper, pv, fv, due) {
  paste0("Pmt(", rate, ", ", nper, ", ", pv, ", ", fv, ", ", due, ")")
}

#' MDX PPmt function
#'
#' Returns a Double specifying the principal payment for a given period of an annuity based on periodic, fixed payments and a fixed interest rate.
#'
#' @param rate A Numeric Expression expression.
#' @param per A Numeric Expression expression.
#' @param nper A Numeric Expression expression.
#' @param pv A Numeric Expression expression.
#' @param fv A Numeric Expression expression (optional).
#' @param due A Logical Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_ppmt <- function(rate, per, nper, pv, fv = NULL, due = NULL) {
  args <- paste0(rate, ", ", per, ", ", nper, ", ", pv)
  if (!is.null(fv)) args <- paste0(args, ", ", fv)
  if (!is.null(due)) args <- paste0(args, ", ", due)
  paste0("PPmt(", args, ")")
}

#' MDX PV function
#'
#' Returns a Double specifying the present value of an annuity based on periodic, fixed payments to be paid in the future and a fixed interest rate.
#'
#' @param rate A Numeric Expression expression.
#' @param nper A Numeric Expression expression.
#' @param pmt A Numeric Expression expression.
#' @param fv A Numeric Expression expression.
#' @param due A Logical Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_pv <- function(rate, nper, pmt, fv, due) {
  paste0("PV(", rate, ", ", nper, ", ", pmt, ", ", fv, ", ", due, ")")
}

#' MDX Rate function
#'
#' Returns a Double specifying the interest rate per period for an annuity.
#'
#' @param nper A Numeric Expression expression.
#' @param pmt A Numeric Expression expression.
#' @param pv A Numeric Expression expression.
#' @param fv A Numeric Expression expression (optional).
#' @param due A Logical Expression expression (optional).
#' @param guess A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_rate <- function(nper, pmt, pv, fv = NULL, due = NULL, guess = NULL) {
  args <- paste0(nper, ", ", pmt, ", ", pv)
  if (!is.null(fv)) args <- paste0(args, ", ", fv)
  if (!is.null(due)) args <- paste0(args, ", ", due)
  if (!is.null(guess)) args <- paste0(args, ", ", guess)
  paste0("Rate(", args, ")")
}

#' MDX Replace function
#'
#' Returns a string in which a specified substring has been replaced with another substring a specified number of times.
#'
#' @param expression A String expression.
#' @param find A String expression.
#' @param replace A String expression.
#' @param start A Integer expression (optional).
#' @param coun A Integer expression (optional).
#' @param compare A Integer expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_replace <- function(expression, find, replace, start = NULL, coun = NULL, compare = NULL) {
  args <- paste0(expression, ", ", find, ", ", replace)
  if (!is.null(start)) args <- paste0(args, ", ", start)
  if (!is.null(coun)) args <- paste0(args, ", ", coun)
  if (!is.null(compare)) args <- paste0(args, ", ", compare)
  paste0("Replace(", args, ")")
}

#' MDX Right function
#'
#' Returns a Variant (String) containing a specified number of characters from the right side of a string.
#'
#' @param sstring A String expression.
#' @param length A Integer expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_right <- function(sstring, length) {
  paste0("Right(", sstring, ", ", length, ")")
}

#' MDX Round function
#'
#' Returns a number rounded to a specified number of decimal places.
#'
#' @param number A Numeric Expression expression.
#' @param digits_after_decimal A Integer expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_round <- function(number, digits_after_decimal = NULL) {
  args <- paste0(number)
  if (!is.null(digits_after_decimal)) args <- paste0(args, ", ", digits_after_decimal)
  paste0("Round(", args, ")")
}

#' MDX RTrim function
#'
#' Returns a Variant (String) containing a copy of a specified string without trailing spaces.
#'
#' @param string A String expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_rtrim <- function(string) {
  paste0("RTrim(", string, ")")
}

#' MDX Second function
#'
#' Returns a Variant (Integer) specifying a whole number between 0 and 59, inclusive, representing the second of the minute.
#'
#' @param date A DateTime expression.
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_second <- function(date) {
  paste0("Second(", date, ")")
}

#' MDX Sgn function
#'
#' Returns a Variant (Integer) indicating the sign of a number.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_sgn <- function(number) {
  paste0("Sgn(", number, ")")
}

#' MDX Sin function
#'
#' Returns a Double specifying the sine of an angle.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_sin <- function(number) {
  paste0("Sin(", number, ")")
}

#' MDX SLN function
#'
#' Returns a Double specifying the straight-line depreciation of an asset for a single period.
#'
#' @param cost A Numeric Expression expression.
#' @param salvage A Numeric Expression expression.
#' @param life A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_sln <- function(cost, salvage, life) {
  paste0("SLN(", cost, ", ", salvage, ", ", life, ")")
}

#' MDX Space function
#'
#' Returns a Variant (String) consisting of the specified number of spaces.
#'
#' @param number A Integer expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_space <- function(number) {
  paste0("Space(", number, ")")
}

#' MDX Sqr function
#'
#' Returns a Double specifying the square root of a number.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_sqr <- function(number) {
  paste0("Sqr(", number, ")")
}

#' MDX Str function
#'
#' Returns a Variant (String) representation of a number.
#'
#' @param number A Value expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_str <- function(number) {
  paste0("Str(", number, ")")
}

#' MDX StrComp function
#'
#' Returns a Variant (Integer) indicating the result of a string comparison.
#'
#' @param string1 A String expression.
#' @param string2 A String expression.
#' @param compare A Integer expression (optional).
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_str_comp <- function(string1, string2, compare = NULL) {
  args <- paste0(string1, ", ", string2)
  if (!is.null(compare)) args <- paste0(args, ", ", compare)
  paste0("StrComp(", args, ")")
}

#' MDX String function
#'
#'
#' @param number A Integer expression.
#' @param character A String expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_string <- function(number, character) {
  paste0("String(", number, ", ", character, ")")
}

#' MDX StrReverse function
#'
#' Returns a string in which the character order of a specified string is reversed.
#'
#' @param string A String expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_str_reverse <- function(string) {
  paste0("StrReverse(", string, ")")
}

#' MDX SYD function
#'
#' Returns a Double specifying the sum-of-years' digits depreciation of an asset for a specified period.
#'
#' @param cost A Numeric Expression expression.
#' @param salvage A Numeric Expression expression.
#' @param life A Numeric Expression expression.
#' @param period A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_syd <- function(cost, salvage, life, period) {
  paste0("SYD(", cost, ", ", salvage, ", ", life, ", ", period, ")")
}

#' MDX Tan function
#'
#' Returns a Double specifying the tangent of an angle.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_tan <- function(number) {
  paste0("Tan(", number, ")")
}

#' MDX Time function
#'
#' Returns a Variant (Date) indicating the current system time.
#'
#' @return MDX string returning DateTime.
#' @family vba
#' @export
mdx_time <- function() {
  paste0("Time()")
}

#' MDX Timer function
#'
#' Returns a Single representing the number of seconds elapsed since midnight.
#'
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_timer <- function() {
  paste0("Timer()")
}

#' MDX TimeSerial function
#'
#' Returns a Variant (Date) containing the time for a specific hour, minute, and second.
#'
#' @param hour A Integer expression.
#' @param minute A Integer expression.
#' @param second A Integer expression.
#' @return MDX string returning DateTime.
#' @family vba
#' @export
mdx_time_serial <- function(hour, minute, second) {
  paste0("TimeSerial(", hour, ", ", minute, ", ", second, ")")
}

#' MDX TimeValue function
#'
#' Returns a Variant (Date) containing the time.
#'
#' @param date A DateTime expression.
#' @return MDX string returning DateTime.
#' @family vba
#' @export
mdx_time_value <- function(date) {
  paste0("TimeValue(", date, ")")
}

#' MDX Trim function
#'
#' Returns a Variant (String) containing a copy of a specified string without leading and trailing spaces.
#'
#' @param string A String expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_trim <- function(string) {
  paste0("Trim(", string, ")")
}

#' MDX TypeName function
#'
#' Returns a String that provides information about a variable.
#'
#' @param var_name A Value expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_type_name <- function(var_name) {
  paste0("TypeName(", var_name, ")")
}

#' MDX Val function
#'
#' VB function Val
#'
#' @param value A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_val <- function(value) {
  paste0("Val(", value, ")")
}

#' MDX Weekday function
#'
#' Returns a Variant (Integer) containing a whole number representing the day of the week.
#'
#' @param date A DateTime expression.
#' @param first_day_of_week A Integer expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family vba
#' @export
mdx_weekday <- function(date, first_day_of_week = NULL) {
  args <- paste0(date)
  if (!is.null(first_day_of_week)) args <- paste0(args, ", ", first_day_of_week)
  paste0("Weekday(", args, ")")
}

#' MDX WeekdayName function
#'
#' Returns a string indicating the specified day of the week.
#'
#' @param weekday A Integer expression.
#' @param abbreviate A Logical Expression expression.
#' @param first_day_of_week A Integer expression.
#' @return MDX string returning String.
#' @family vba
#' @export
mdx_weekday_name <- function(weekday, abbreviate, first_day_of_week) {
  paste0("WeekdayName(", weekday, ", ", abbreviate, ", ", first_day_of_week, ")")
}

#' MDX Year function
#'
#' Returns a Variant (Integer) containing a whole number representing the year.
#'
#' @param date A DateTime expression.
#' @return MDX string returning Integer.
#' @family vba
#' @export
mdx_year <- function(date) {
  paste0("Year(", date, ")")
}

