#' @title MDX Drill Functions (auto-generated)
#' @description Auto-generated MDX function wrappers for drill.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX DrilldownLevel function
#'
#' Drills down the members of a set, at a specified level, to one level below. Alternatively, drills down on a specified dimension in the set.
#'
#' @param set_expr A Set expression.
#' @param level A Level expression (optional).
#' @param index A Numeric Expression expression (optional).
#' @param include_members A Symbol expression (optional).
#' @return MDX string returning Set.
#' @family drill
#' @export
mdx_drilldown_level <- function(set_expr, level = NULL, index = NULL, include_members = NULL) {
  args <- paste0(set_expr)
  if (!is.null(level)) args <- paste0(args, ", ", level)
  if (!is.null(index)) args <- paste0(args, ", ", index)
  if (!is.null(include_members)) args <- paste0(args, ", ", include_members)
  paste0("DrilldownLevel(", args, ")")
}

#' MDX DrilldownLevelBottom function
#'
#' Drills down the bottommost members of a set, at a specified level, to one level below.
#'
#' @param set_expr A Set expression.
#' @param count A Numeric Expression expression.
#' @param level A Level expression (optional).
#' @param numeric_expression A Numeric Expression expression (optional).
#' @return MDX string returning Set.
#' @family drill
#' @export
mdx_drilldown_level_bottom <- function(set_expr, count, level = NULL, numeric_expression = NULL) {
  args <- paste0(set_expr, ", ", count)
  if (!is.null(level)) args <- paste0(args, ", ", level)
  if (!is.null(numeric_expression)) args <- paste0(args, ", ", numeric_expression)
  paste0("DrilldownLevelBottom(", args, ")")
}

#' MDX DrilldownLevelTop function
#'
#' Drills down the topmost members of a set, at a specified level, to one level below.
#'
#' @param set_expr A Set expression.
#' @param count A Numeric Expression expression.
#' @param level A Level expression (optional).
#' @param numeric_expression A Numeric Expression expression (optional).
#' @return MDX string returning Set.
#' @family drill
#' @export
mdx_drilldown_level_top <- function(set_expr, count, level = NULL, numeric_expression = NULL) {
  args <- paste0(set_expr, ", ", count)
  if (!is.null(level)) args <- paste0(args, ", ", level)
  if (!is.null(numeric_expression)) args <- paste0(args, ", ", numeric_expression)
  paste0("DrilldownLevelTop(", args, ")")
}

#' MDX DrilldownMember function
#'
#' Drills down the members in a set that are present in a second specified set.
#'
#' @param set1 A Set expression.
#' @param set2 A Set expression.
#' @param recursive A Symbol expression (optional).
#' @return MDX string returning Set.
#' @family drill
#' @export
mdx_drilldown_member <- function(set1, set2, recursive = NULL) {
  args <- paste0(set1, ", ", set2)
  if (!is.null(recursive)) args <- paste0(args, ", ", recursive)
  paste0("DrilldownMember(", args, ")")
}

#' MDX ToggleDrillState function
#'
#' Toggles the drill state of members. This function is a combination of DrillupMember and DrilldownMember.
#'
#' @param set1 A Set expression.
#' @param set2 A Set expression.
#' @param recursive A Symbol expression (optional).
#' @return MDX string returning Set.
#' @family drill
#' @export
mdx_toggle_drill_state <- function(set1, set2, recursive = NULL) {
  args <- paste0(set1, ", ", set2)
  if (!is.null(recursive)) args <- paste0(args, ", ", recursive)
  paste0("ToggleDrillState(", args, ")")
}

