#' @title MDX Type Introspection Functions (auto-generated)
#' @description Auto-generated MDX function wrappers for type-introspection.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX AllMembers function
#'
#' Returns a set that contains all members, including calculated members, of the specified hierarchy.
#'
#' @param hierarchy A Hierarchy expression.
#' @return MDX string returning Set.
#' @family type-introspection
#' @export
mdx_hierarchy_all_members <- function(hierarchy) {
  paste0(hierarchy, ".AllMembers")
}

#' MDX Caption function
#'
#' Returns the caption of a dimension.
#'
#' @param dimension A Dimension expression.
#' @return MDX string returning String.
#' @family type-introspection
#' @export
mdx_dimension_caption <- function(dimension) {
  paste0(dimension, ".Caption")
}

#' MDX Dimension function
#'
#' Returns the dimension that contains a specified level.
#'
#' @param level A Level expression.
#' @return MDX string returning Dimension.
#' @family type-introspection
#' @export
mdx_level_dimension <- function(level) {
  paste0(level, ".Dimension")
}

#' MDX Dimensions function
#'
#' Returns the hierarchy whose zero-based position within the cube is specified by a numeric expression.
#'
#' @param numeric_expression A Numeric Expression expression.
#' @return MDX string returning Hierarchy.
#' @family type-introspection
#' @export
mdx_dimensions <- function(numeric_expression) {
  paste0("Dimensions(", numeric_expression, ")")
}

#' MDX Hierarchy function
#'
#' Returns a level's hierarchy.
#'
#' @param member A Level expression.
#' @return MDX string returning Hierarchy.
#' @family type-introspection
#' @export
mdx_level_hierarchy <- function(member) {
  paste0(member, ".Hierarchy")
}

#' MDX Level function
#'
#' Returns a member's level.
#'
#' @param member A Member expression.
#' @return MDX string returning Level.
#' @family type-introspection
#' @export
mdx_member_level <- function(member) {
  paste0(member, ".Level")
}

#' MDX Levels function
#'
#' Returns the level whose name is specified by a string expression.
#'
#' @param hierarchy A Hierarchy expression.
#' @param string A String expression.
#' @return MDX string returning Level.
#' @family type-introspection
#' @export
mdx_levels <- function(hierarchy, string) {
  args <- ""
  args <- if (nchar(args) > 0) paste0(args, ", ", string) else string
  paste0(hierarchy, ".Levels(", args, ")")
}

#' MDX Levels function
#'
#' Returns the level whose name is specified by a string expression.
#'
#' @param string A String expression.
#' @return MDX string returning Level.
#' @family type-introspection
#' @export
mdx_levels <- function(string) {
  paste0("Levels(", string, ")")
}

#' MDX Members function
#'
#' Returns the last child of the parent of a member.
#'
#' @param string A String expression.
#' @return MDX string returning Member.
#' @family type-introspection
#' @export
mdx_members <- function(string) {
  paste0("Members(", string, ")")
}

#' MDX Members function
#'
#' Returns the set of members in a level.
#'
#' @param level A Level expression.
#' @return MDX string returning Set.
#' @family type-introspection
#' @export
mdx_level_members <- function(level) {
  paste0(level, ".Members")
}

#' MDX Name function
#'
#' Returns the name of a dimension.
#'
#' @param dimension A Dimension expression.
#' @return MDX string returning String.
#' @family type-introspection
#' @export
mdx_dimension_name <- function(dimension) {
  paste0(dimension, ".Name")
}

#' MDX Ordinal function
#'
#' Returns the zero-based ordinal value associated with a level.
#'
#' @param level A Level expression.
#' @return MDX string returning Numeric Expression.
#' @family type-introspection
#' @export
mdx_level_ordinal <- function(level) {
  paste0(level, ".Ordinal")
}

#' MDX Unique_Name function
#'
#' Returns the unique name of a member.
#'
#' @param member A Member expression.
#' @return MDX string returning String.
#' @family type-introspection
#' @export
mdx_member_unique_name <- function(member) {
  paste0(member, ".Unique_Name")
}

#' MDX UniqueName function
#'
#' Returns the unique name of a dimension.
#'
#' @param dimension A Dimension expression.
#' @return MDX string returning String.
#' @family type-introspection
#' @export
mdx_dimension_unique_name <- function(dimension) {
  paste0(dimension, ".UniqueName")
}

#' MDX Value function
#'
#' Returns the value of a measure.
#'
#' @param member A Member expression.
#' @return MDX string returning Numeric Expression.
#' @family type-introspection
#' @export
mdx_value <- function(member) {
  paste0(member, ".Value")
}

