#' @title MDX Conditional Functions (auto-generated)
#' @description Auto-generated MDX function wrappers for conditional.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX IIf function
#'
#' Returns one of two dimension values determined by a logical test.
#'
#' @param condition A Logical Expression expression.
#' @param dimension1 A Dimension expression.
#' @param dimension2 A Dimension expression.
#' @return MDX string returning Dimension.
#' @family conditional
#' @export
mdx_iif <- function(condition, dimension1, dimension2) {
  paste0("IIf(", condition, ", ", dimension1, ", ", dimension2, ")")
}

#' MDX IsEmpty function
#'
#' Determines if an expression evaluates to the empty cell value.
#'
#' @param value A String expression.
#' @return MDX string returning Logical Expression.
#' @family conditional
#' @export
mdx_is_empty <- function(value) {
  paste0("IsEmpty(", value, ")")
}

#' MDX IsNull function
#'
#' Returns a Boolean value that indicates whether an expression contains no valid data (Null).
#'
#' @param var_name A Value expression.
#' @return MDX string returning Logical Expression.
#' @family conditional
#' @export
mdx_is_null <- function(var_name) {
  paste0("IsNull(", var_name, ")")
}

