#' @title MDX String Functions (auto-generated)
#' @description Auto-generated MDX function wrappers for string.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX Format function
#'
#' Formats a number or date to a string.
#'
#' @param value A Member expression.
#' @param format A String expression.
#' @return MDX string returning String.
#' @family string
#' @export
mdx_format <- function(value, format) {
  paste0("Format(", value, ", ", format, ")")
}

#' MDX LCase function
#'
#' Returns a String that has been converted to lowercase.
#'
#' @param string A String expression.
#' @return MDX string returning String.
#' @family string
#' @export
mdx_lcase <- function(string) {
  paste0("LCase(", string, ")")
}

#' MDX Len function
#'
#' Returns the number of characters in a string
#'
#' @param string A String expression.
#' @return MDX string returning Numeric Expression.
#' @family string
#' @export
mdx_len <- function(string) {
  paste0("Len(", string, ")")
}

#' MDX StrToSet function
#'
#' Constructs a set from a string expression.
#'
#' @param string_expr A String expression.
#' @return MDX string returning Set.
#' @family string
#' @export
mdx_str_to_set <- function(string_expr) {
  paste0("StrToSet(", string_expr, ")")
}

#' MDX StrToTuple function
#'
#' Constructs a tuple from a string.
#'
#' @param string_expr A String expression.
#' @return MDX string returning Tuple.
#' @family string
#' @export
mdx_str_to_tuple <- function(string_expr) {
  paste0("StrToTuple(", string_expr, ")")
}

#' MDX TupleToStr function
#'
#' Constructs a string from a tuple.
#'
#' @param tuple A Tuple expression.
#' @return MDX string returning String.
#' @family string
#' @export
mdx_tuple_to_str <- function(tuple) {
  paste0("TupleToStr(", tuple, ")")
}

#' MDX UCase function
#'
#' Returns a string that has been converted to uppercase
#'
#' @param string A String expression.
#' @return MDX string returning String.
#' @family string
#' @export
mdx_ucase <- function(string) {
  paste0("UCase(", string, ")")
}

