#' @title MDX Operators (auto-generated)
#' @description Auto-generated MDX function wrappers for operators.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX * function
#'
#' Returns the cross product of two sets.
#'
#' @param numeric1 A Set expression.
#' @param numeric2 A Set expression.
#' @return MDX string returning Set.
#' @family operators
#' @export
mdx_multiply <- function(numeric1, numeric2) {
  paste0("(", numeric1, " * ", numeric2, ")")
}

#' MDX + function
#'
#' Adds two numbers.
#'
#' @param numeric1 A Numeric Expression expression.
#' @param numeric1_2 A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family operators
#' @export
mdx_plus <- function(numeric1, numeric1_2) {
  paste0("(", numeric1, " + ", numeric1_2, ")")
}

#' MDX - function
#'
#' Returns the negative of a number.
#'
#' @param numeric_expr A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family operators
#' @export
mdx_minus <- function(numeric_expr) {
  paste0("- ", numeric_expr)
}

#' MDX - function
#'
#' Subtracts two numbers.
#'
#' @param numeric1 A Numeric Expression expression.
#' @param numeric2 A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family operators
#' @export
mdx_minus <- function(numeric1, numeric2) {
  paste0("(", numeric1, " - ", numeric2, ")")
}

#' MDX / function
#'
#' Divides two numbers.
#'
#' @param numeric1 A Numeric Expression expression.
#' @param numeric2 A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family operators
#' @export
mdx_divide <- function(numeric1, numeric2) {
  paste0("(", numeric1, " / ", numeric2, ")")
}

#' MDX : function
#'
#' Infix colon operator returns the set of members between a given pair of members.
#'
#' @param member1 A Member expression.
#' @param member2 A Member expression.
#' @return MDX string returning Set.
#' @family operators
#' @export
mdx_ <- function(member1, member2) {
  paste0("(", member1, " : ", member2, ")")
}

#' MDX < function
#'
#' Returns whether an expression is less than another.
#'
#' @param numeric1 A Numeric Expression expression.
#' @param numeric2 A Numeric Expression expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_less <- function(numeric1, numeric2) {
  paste0("(", numeric1, " < ", numeric2, ")")
}

#' MDX <= function
#'
#' Returns whether an expression is less than or equal to another.
#'
#' @param string1 A String expression.
#' @param string2 A String expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_less_equal <- function(string1, string2) {
  paste0("(", string1, " <= ", string2, ")")
}

#' MDX <> function
#'
#' Returns whether two expressions are not equal.
#'
#' @param numeric1 A Numeric Expression expression.
#' @param numeric2 A Numeric Expression expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_not_equal <- function(numeric1, numeric2) {
  paste0("(", numeric1, " <> ", numeric2, ")")
}

#' MDX = function
#'
#' Returns whether two expressions are equal.
#'
#' @param numeric1 A Numeric Expression expression.
#' @param numeric2 A Numeric Expression expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_equal <- function(numeric1, numeric2) {
  paste0("(", numeric1, " = ", numeric2, ")")
}

#' MDX > function
#'
#' Returns whether an expression is greater than another.
#'
#' @param numeric1 A Numeric Expression expression.
#' @param numeric2 A Numeric Expression expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_greater <- function(numeric1, numeric2) {
  paste0("(", numeric1, " > ", numeric2, ")")
}

#' MDX >= function
#'
#' Returns whether an expression is greater than or equal to another.
#'
#' @param numeric1 A Numeric Expression expression.
#' @param numeric2 A Numeric Expression expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_greater_equal <- function(numeric1, numeric2) {
  paste0("(", numeric1, " >= ", numeric2, ")")
}

#' MDX AND function
#'
#' Returns the conjunction of two conditions.
#'
#' @param condition1 A Logical Expression expression.
#' @param condition2 A Logical Expression expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_and <- function(condition1, condition2) {
  paste0("(", condition1, " AND ", condition2, ")")
}

#' MDX IN function
#'
#' Returns true if the member argument is contained in the set argument.
#'
#' @param member A Member expression.
#' @param set_expr A Set expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_in <- function(member, set_expr) {
  paste0("(", member, " IN ", set_expr, ")")
}

#' MDX IS function
#'
#' Returns whether two objects are the same
#'
#' @param member1 A Member expression.
#' @param member2 A Member expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_is <- function(member1, member2) {
  paste0("(", member1, " IS ", member2, ")")
}

#' MDX IS EMPTY function
#'
#' A shortcut function for the PeriodsToDate function that specifies the level to be Month.
#'
#' @param member A Member expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_is_empty <- function(member) {
  paste0(member, " IS EMPTY")
}

#' MDX IS NULL function
#'
#' Returns whether an object is null
#'
#' @param member A Member expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_is_null <- function(member) {
  paste0(member, " IS NULL")
}

#' MDX MATCHES function
#'
#' Returns true if the string matches the regular expression.
#'
#' @param string A String expression.
#' @param regex A String expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_matches <- function(string, regex) {
  paste0("(", string, " MATCHES ", regex, ")")
}

#' MDX NOT function
#'
#' Returns the negation of a condition.
#'
#' @param condition A Logical Expression expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_not <- function(condition) {
  paste0("NOT ", condition)
}

#' MDX OR function
#'
#' Returns the disjunction of two conditions.
#'
#' @param condition1 A Logical Expression expression.
#' @param condition2 A Logical Expression expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_or <- function(condition1, condition2) {
  paste0("(", condition1, " OR ", condition2, ")")
}

#' MDX XOR function
#'
#' Returns whether two conditions are mutually exclusive.
#'
#' @param condition1 A Logical Expression expression.
#' @param condition1_2 A Logical Expression expression.
#' @return MDX string returning Logical Expression.
#' @family operators
#' @export
mdx_xor <- function(condition1, condition1_2) {
  paste0("(", condition1, " XOR ", condition1_2, ")")
}

#' MDX || function
#'
#' Concatenates two strings.
#'
#' @param string1 A String expression.
#' @param string2 A String expression.
#' @return MDX string returning String.
#' @family operators
#' @export
mdx_ <- function(string1, string2) {
  paste0("(", string1, " || ", string2, ")")
}

