#' @title MDX Excel Functions (auto-generated)
#' @description Auto-generated MDX function wrappers for excel.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX Cosh function
#'
#' Returns the hyperbolic cosine of a number.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family excel
#' @export
mdx_cosh <- function(number) {
  paste0("Cosh(", number, ")")
}

#' MDX Degrees function
#'
#' Converts radians to degrees.
#'
#' @param radians A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family excel
#' @export
mdx_degrees <- function(radians) {
  paste0("Degrees(", radians, ")")
}

#' MDX Log10 function
#'
#' Returns the base-10 logarithm of a number.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family excel
#' @export
mdx_log10 <- function(number) {
  paste0("Log10(", number, ")")
}

#' MDX Mod function
#'
#' Returns the remainder of dividing n by d.
#'
#' @param n A Value expression.
#' @param d A Value expression.
#' @return MDX string returning Numeric Expression.
#' @family excel
#' @export
mdx_mod <- function(n, d) {
  paste0("Mod(", n, ", ", d, ")")
}

#' MDX Pi function
#'
#' Returns the number 3.14159265358979, the mathematical constant pi, accurate to 15 digits.
#'
#' @return MDX string returning Numeric Expression.
#' @family excel
#' @export
mdx_pi <- function() {
  paste0("Pi()")
}

#' MDX Power function
#'
#' Returns the result of a number raised to a power.
#'
#' @param x A Numeric Expression expression.
#' @param y A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family excel
#' @export
mdx_power <- function(x, y) {
  paste0("Power(", x, ", ", y, ")")
}

#' MDX Radians function
#'
#' Converts degrees to radians.
#'
#' @param radians A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family excel
#' @export
mdx_radians <- function(radians) {
  paste0("Radians(", radians, ")")
}

#' MDX Sinh function
#'
#' Returns the hyperbolic sine of a number.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family excel
#' @export
mdx_sinh <- function(number) {
  paste0("Sinh(", number, ")")
}

#' MDX SqrtPi function
#'
#' Returns the square root of (number * pi).
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family excel
#' @export
mdx_sqrt_pi <- function(number) {
  paste0("SqrtPi(", number, ")")
}

#' MDX Tanh function
#'
#' Returns the hyperbolic tangent of a number.
#'
#' @param radians A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family excel
#' @export
mdx_tanh <- function(radians) {
  paste0("Tanh(", radians, ")")
}

