#' @title MDX Time Functions (auto-generated)
#' @description Auto-generated MDX function wrappers for time.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX ClosingPeriod function
#'
#' Returns the last descendant of a member at a level.
#'
#' @param level A Level expression (optional).
#' @param member A Member expression (optional).
#' @return MDX string returning Member.
#' @family time
#' @export
mdx_closing_period <- function(level = NULL, member = NULL) {
  args <- paste0()
  if (!is.null(level)) args <- paste0(args, ", ", level)
  if (!is.null(member)) args <- paste0(args, ", ", member)
  paste0("ClosingPeriod(", args, ")")
}

#' MDX LastPeriods function
#'
#' Returns a set of members prior to and including a specified member.
#'
#' @param index A Numeric Expression expression.
#' @param member A Member expression (optional).
#' @return MDX string returning Set.
#' @family time
#' @export
mdx_last_periods <- function(index, member = NULL) {
  args <- paste0(index)
  if (!is.null(member)) args <- paste0(args, ", ", member)
  paste0("LastPeriods(", args, ")")
}

#' MDX Mtd function
#'
#' A shortcut function for the PeriodsToDate function that specifies the level to be Month.
#'
#' @param member A Member expression (optional).
#' @return MDX string returning Set.
#' @family time
#' @export
mdx_mtd <- function(member = NULL) {
  args <- paste0()
  if (!is.null(member)) args <- paste0(args, ", ", member)
  paste0("Mtd(", args, ")")
}

#' MDX OpeningPeriod function
#'
#' Returns the first descendant of a member at a level.
#'
#' @param level A Level expression (optional).
#' @param member A Member expression (optional).
#' @return MDX string returning Member.
#' @family time
#' @export
mdx_opening_period <- function(level = NULL, member = NULL) {
  args <- paste0()
  if (!is.null(level)) args <- paste0(args, ", ", level)
  if (!is.null(member)) args <- paste0(args, ", ", member)
  paste0("OpeningPeriod(", args, ")")
}

#' MDX ParallelPeriod function
#'
#' Returns a member from a prior period in the same relative position as a specified member.
#'
#' @param level A Level expression (optional).
#' @param numeric_expr A Numeric Expression expression (optional).
#' @param member A Member expression (optional).
#' @return MDX string returning Member.
#' @family time
#' @export
mdx_parallel_period <- function(level = NULL, numeric_expr = NULL, member = NULL) {
  args <- paste0()
  if (!is.null(level)) args <- paste0(args, ", ", level)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  if (!is.null(member)) args <- paste0(args, ", ", member)
  paste0("ParallelPeriod(", args, ")")
}

#' MDX PeriodsToDate function
#'
#' Returns a set of periods (members) from a specified level starting with the first period and ending with a specified member.
#'
#' @param set_expr A Set expression (optional).
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Set.
#' @family time
#' @export
mdx_periods_to_date <- function(set_expr = NULL, numeric_expr = NULL) {
  args <- paste0()
  if (!is.null(set_expr)) args <- paste0(args, ", ", set_expr)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("PeriodsToDate(", args, ")")
}

#' MDX Qtd function
#'
#' A shortcut function for the PeriodsToDate function that specifies the level to be Quater.
#'
#' @param member A Member expression (optional).
#' @return MDX string returning Set.
#' @family time
#' @export
mdx_qtd <- function(member = NULL) {
  args <- paste0()
  if (!is.null(member)) args <- paste0(args, ", ", member)
  paste0("Qtd(", args, ")")
}

#' MDX Wtd function
#'
#' A shortcut function for the PeriodsToDate function that specifies the level to be Week.
#'
#' @param member A Member expression (optional).
#' @return MDX string returning Set.
#' @family time
#' @export
mdx_wtd <- function(member = NULL) {
  args <- paste0()
  if (!is.null(member)) args <- paste0(args, ", ", member)
  paste0("Wtd(", args, ")")
}

#' MDX Ytd function
#'
#' A shortcut function for the PeriodsToDate function that specifies the level to be Year.
#'
#' @param member A Member expression (optional).
#' @return MDX string returning Set.
#' @family time
#' @export
mdx_ytd <- function(member = NULL) {
  args <- paste0()
  if (!is.null(member)) args <- paste0(args, ", ", member)
  paste0("Ytd(", args, ")")
}

