#' @title MDX Set Operations (auto-generated)
#' @description Auto-generated MDX function wrappers for set-operations.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX Distinct function
#'
#' Eliminates duplicate tuples from a set.
#'
#' @param set_expr A Set expression.
#' @return MDX string returning Set.
#' @family set-operations
#' @export
mdx_distinct <- function(set_expr) {
  paste0("Distinct(", set_expr, ")")
}

#' MDX Except function
#'
#' Finds the difference between two sets, optionally retaining duplicates.
#'
#' @param set1 A Set expression.
#' @param set2 A Set expression.
#' @param all A Symbol expression (optional).
#' @return MDX string returning Set.
#' @family set-operations
#' @export
mdx_except <- function(set1, set2, all = NULL) {
  args <- paste0(set1, ", ", set2)
  if (!is.null(all)) args <- paste0(args, ", ", all)
  paste0("Except(", args, ")")
}

#' MDX Existing function
#'
#' Forces the set to be evaluated within the current context.
#'
#' @param set_expr A Set expression.
#' @return MDX string returning Set.
#' @family set-operations
#' @export
mdx_existing <- function(set_expr) {
  paste0("Existing ", set_expr)
}

#' MDX Exists function
#'
#' Returns the the set of tuples of the first set that exist with one or more tuples of the second set.
#'
#' @param set1 A Set expression.
#' @param set2 A Set expression.
#' @return MDX string returning Set.
#' @family set-operations
#' @export
mdx_exists <- function(set1, set2) {
  paste0("Exists(", set1, ", ", set2, ")")
}

#' MDX Filter function
#'
#' Returns the set resulting from filtering a set based on a search condition.
#'
#' @param set_expr A Set expression.
#' @param logical_expr A Logical Expression expression.
#' @return MDX string returning Set.
#' @family set-operations
#' @export
mdx_filter <- function(set_expr, logical_expr) {
  paste0("Filter(", set_expr, ", ", logical_expr, ")")
}

#' MDX Generate function
#'
#' Applies a set to each member of another set and joins the resulting sets by union.
#'
#' @param set1 A Set expression.
#' @param set2 A Set expression.
#' @param all A Symbol expression (optional).
#' @return MDX string returning Set.
#' @family set-operations
#' @export
mdx_generate <- function(set1, set2, all = NULL) {
  args <- paste0(set1, ", ", set2)
  if (!is.null(all)) args <- paste0(args, ", ", all)
  paste0("Generate(", args, ")")
}

#' MDX Hierarchize function
#'
#' Orders the members of a set in a hierarchy.
#'
#' @param set_expr A Set expression.
#' @param pre_post A Symbol expression (optional).
#' @return MDX string returning Set.
#' @family set-operations
#' @export
mdx_hierarchize <- function(set_expr, pre_post = NULL) {
  args <- paste0(set_expr)
  if (!is.null(pre_post)) args <- paste0(args, ", ", pre_post)
  paste0("Hierarchize(", args, ")")
}

#' MDX NativizeSet function
#'
#' Tries to natively evaluate <Set>.
#'
#' @param set_expr A Set expression.
#' @return MDX string returning Set.
#' @family set-operations
#' @export
mdx_nativize_set <- function(set_expr) {
  paste0("NativizeSet(", set_expr, ")")
}

#' MDX NonEmpty function
#'
#' Returns the set of tuples that are not empty from a specified set, based on the cross product of the specified set with a second set.
#'
#' @param set1 A Set expression.
#' @param set2 A Set expression (optional).
#' @return MDX string returning Set.
#' @family set-operations
#' @export
mdx_non_empty <- function(set1, set2 = NULL) {
  args <- paste0(set1)
  if (!is.null(set2)) args <- paste0(args, ", ", set2)
  paste0("NonEmpty(", args, ")")
}

#' MDX NonEmptyCrossJoin function
#'
#' Returns the cross product of two sets, excluding empty tuples and tuples without associated fact table data.
#'
#' @param set1 A Set expression.
#' @param set2 A Set expression.
#' @return MDX string returning Set.
#' @family set-operations
#' @export
mdx_non_empty_cross_join <- function(set1, set2) {
  paste0("NonEmptyCrossJoin(", set1, ", ", set2, ")")
}

#' MDX Union function
#'
#' Returns the union of two sets, optionally retaining duplicates.
#'
#' @param set1 A Set expression.
#' @param set2 A Set expression.
#' @param all A Symbol expression (optional).
#' @return MDX string returning Set.
#' @family set-operations
#' @export
mdx_union <- function(set1, set2, all = NULL) {
  args <- paste0(set1, ", ", set2)
  if (!is.null(all)) args <- paste0(args, ", ", all)
  paste0("Union(", args, ")")
}

#' MDX Unorder function
#'
#' Removes any enforced ordering from a specified set.
#'
#' @param set_expr A Set expression.
#' @return MDX string returning Set.
#' @family set-operations
#' @export
mdx_unorder <- function(set_expr) {
  paste0("Unorder(", set_expr, ")")
}

