#' @title MDX Aggregate Functions (auto-generated)
#' @description Auto-generated MDX function wrappers for aggregate.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX Aggregate function
#'
#' Returns a calculated value using the appropriate aggregate function, based on the context of the query.
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family aggregate
#' @export
mdx_aggregate <- function(set_expr, numeric_expr = NULL) {
  args <- paste0(set_expr)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("Aggregate(", args, ")")
}

#' MDX Avg function
#'
#' Returns the average value of a numeric expression evaluated over a set.
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family aggregate
#' @export
mdx_avg <- function(set_expr, numeric_expr = NULL) {
  args <- paste0(set_expr)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("Avg(", args, ")")
}

#' MDX Count function
#'
#' Returns the number of tuples in a set, empty cells included unless the optional EXCLUDEEMPTY flag is used.
#'
#' @param set_expr A Set expression.
#' @param pre_post A Symbol expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family aggregate
#' @export
mdx_count <- function(set_expr, pre_post = NULL) {
  args <- paste0(set_expr)
  if (!is.null(pre_post)) args <- paste0(args, ", ", pre_post)
  paste0("Count(", args, ")")
}

#' MDX Count function
#'
#' Returns the number of tuples in a set including empty cells.
#'
#' @param set_expr A Set expression.
#' @return MDX string returning Numeric Expression.
#' @family aggregate
#' @export
mdx_set_count <- function(set_expr) {
  paste0(set_expr, ".Count")
}

#' MDX Max function
#'
#' Returns the maximum value of a numeric expression evaluated over a set.
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family aggregate
#' @export
mdx_max <- function(set_expr, numeric_expr = NULL) {
  args <- paste0(set_expr)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("Max(", args, ")")
}

#' MDX Median function
#'
#' Returns the median value of a numeric expression evaluated over a set.
#'
#' @param set_expr A Set expression.
#' @param percentile A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family aggregate
#' @export
mdx_median <- function(set_expr, percentile = NULL) {
  args <- paste0(set_expr)
  if (!is.null(percentile)) args <- paste0(args, ", ", percentile)
  paste0("Median(", args, ")")
}

#' MDX Min function
#'
#' Returns the minimum value of a numeric expression evaluated over a set.
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family aggregate
#' @export
mdx_min <- function(set_expr, numeric_expr = NULL) {
  args <- paste0(set_expr)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("Min(", args, ")")
}

#' MDX Sum function
#'
#' Returns the sum of a numeric expression evaluated over a set.
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family aggregate
#' @export
mdx_sum <- function(set_expr, numeric_expr = NULL) {
  args <- paste0(set_expr)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("Sum(", args, ")")
}

