#' @title MDX other Functions (auto-generated)
#' @description Auto-generated MDX function wrappers for other.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX Acos function
#'
#' Returns the arccosine, or inverse cosine, of a number. The arccosine is the angle whose cosine is Arg1. The returned angle is given in radians in the range 0 (zero) to pi.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family other
#' @export
mdx_acos <- function(number) {
  paste0("Acos(", number, ")")
}

#' MDX Acosh function
#'
#' Returns the inverse hyperbolic cosine of a number. Number must be greater than or equal to 1. The inverse hyperbolic cosine is the value whose hyperbolic cosine is Arg1, so Acosh(Cosh(number)) equals Arg1.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family other
#' @export
mdx_acosh <- function(number) {
  paste0("Acosh(", number, ")")
}

#' MDX AscB function
#'
#' Returns an Integer representing the character code corresponding to the first letter in a string.
#'
#' @param string A String expression.
#' @return MDX string returning Integer.
#' @family other
#' @export
mdx_asc_b <- function(string) {
  paste0("AscB(", string, ")")
}

#' MDX Asinh function
#'
#' Returns the inverse hyperbolic sine of a number. The inverse hyperbolic sine is the value whose hyperbolic sine is Arg1, so Asinh(Sinh(number)) equals Arg1.
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family other
#' @export
mdx_asinh <- function(number) {
  paste0("Asinh(", number, ")")
}

#' MDX Atan2 function
#'
#' Returns the arctangent, or inverse tangent, of the specified x- and y-coordinates. The arctangent is the angle from the x-axis to a line containing the origin (0, 0) and a point with coordinates (x_num, y_num). The angle is given in radians between -pi and pi, excluding -pi.
#'
#' @param x A Numeric Expression expression.
#' @param y A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family other
#' @export
mdx_atan2 <- function(x, y) {
  paste0("Atan2(", x, ", ", y, ")")
}

#' MDX Atanh function
#'
#' Returns the inverse hyperbolic tangent of a number. Number must be between -1 and 1 (excluding -1 and 1).
#'
#' @param number A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family other
#' @export
mdx_atanh <- function(number) {
  paste0("Atanh(", number, ")")
}

#' MDX CachedExists function
#'
#' Returns tuples from a non-dynamic <Set> that exists in the specified <Tuple>.  This function will build a query level cache named <String> based on the <Tuple> type.
#'
#' @param set_expr A Set expression.
#' @param tuple A Tuple expression.
#' @param string A String expression.
#' @return MDX string returning Set.
#' @family other
#' @export
mdx_cached_exists <- function(set_expr, tuple, string) {
  paste0("CachedExists(", set_expr, ", ", tuple, ", ", string, ")")
}

#' MDX CovarianceN function
#'
#' Returns the covariance of two series evaluated over a set (unbiased).
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression.
#' @param numeric_expr_3 A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family other
#' @export
mdx_covariance_n <- function(set_expr, numeric_expr, numeric_expr_3 = NULL) {
  args <- paste0(set_expr, ", ", numeric_expr)
  if (!is.null(numeric_expr_3)) args <- paste0(args, ", ", numeric_expr_3)
  paste0("CovarianceN(", args, ")")
}

#' MDX Current function
#'
#' Returns the current member or tuple of a named set.
#'
#' @param set_expr A Set expression.
#' @return MDX string returning Tuple.
#' @family other
#' @export
mdx_current <- function(set_expr) {
  paste0(set_expr, ".Current")
}

#' MDX CurrentOrdinal function
#'
#' Returns the ordinal of the current iteration through a named set.
#'
#' @param set_expr A Set expression.
#' @return MDX string returning Integer.
#' @family other
#' @export
mdx_current_ordinal <- function(set_expr) {
  paste0(set_expr, ".CurrentOrdinal")
}

#' MDX Level_Number function
#'
#' Returns the level number of a member.
#'
#' @param member A Member expression.
#' @return MDX string returning Integer.
#' @family other
#' @export
mdx_level_number <- function(member) {
  paste0(member, ".Level_Number")
}

#' MDX Member_Caption function
#'
#' Returns the caption of a member.
#'
#' @param member A Member expression.
#' @return MDX string returning String.
#' @family other
#' @export
mdx_member_caption <- function(member) {
  paste0(member, ".Member_Caption")
}

#' MDX OrderKey function
#'
#' Returns the member order key.
#'
#' @param member A Member expression.
#' @return MDX string returning Value.
#' @family other
#' @export
mdx_order_key <- function(member) {
  paste0(member, ".OrderKey")
}

#' MDX Parameter function
#'
#' Returns default value of parameter.
#'
#' @param name A String expression.
#' @param type A Symbol expression.
#' @param default_value A String expression.
#' @param description A String expression (optional).
#' @return MDX string returning String.
#' @family other
#' @export
mdx_parameter <- function(name, type, default_value, description = NULL) {
  args <- paste0(name, ", ", type, ", ", default_value)
  if (!is.null(description)) args <- paste0(args, ", ", description)
  paste0("Parameter(", args, ")")
}

#' MDX ParamRef function
#'
#' Returns the current value of this parameter. If it is null, returns the default value.
#'
#' @param name A String expression.
#' @return MDX string returning Value.
#' @family other
#' @export
mdx_param_ref <- function(name) {
  paste0("ParamRef(", name, ")")
}

#' MDX Stddev function
#'
#' Alias for Stdev.
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family other
#' @export
mdx_stddev <- function(set_expr, numeric_expr = NULL) {
  args <- paste0(set_expr)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("Stddev(", args, ")")
}

#' MDX StddevP function
#'
#' Alias for StdevP.
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family other
#' @export
mdx_stddev_p <- function(set_expr, numeric_expr = NULL) {
  args <- paste0(set_expr)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("StddevP(", args, ")")
}

#' MDX ThirdQ function
#'
#' Returns the 3rd quartile value of a numeric expression evaluated over a set.
#'
#' @param set_expr A Set expression.
#' @param range A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family other
#' @export
mdx_third_q <- function(set_expr, range = NULL) {
  args <- paste0(set_expr)
  if (!is.null(range)) args <- paste0(args, ", ", range)
  paste0("ThirdQ(", args, ")")
}

#' MDX Variance function
#'
#' Alias for Var.
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family other
#' @export
mdx_variance <- function(set_expr, numeric_expr = NULL) {
  args <- paste0(set_expr)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("Variance(", args, ")")
}

#' MDX VarianceP function
#'
#' Alias for VarP.
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family other
#' @export
mdx_variance_p <- function(set_expr, numeric_expr = NULL) {
  args <- paste0(set_expr)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("VarianceP(", args, ")")
}

