#' @title MDX Member Navigation (auto-generated)
#' @description Auto-generated MDX function wrappers for member-navigation.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX Ancestor function
#'
#' Returns the ancestor of a member at a specified level.
#'
#' @param member A Member expression.
#' @param level A Level expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_ancestor <- function(member, level) {
  paste0("Ancestor(", member, ", ", level, ")")
}

#' MDX Ancestors function
#'
#' Returns the set of all ancestors of a specified member at a specified level or at a specified distance from the member
#'
#' @param member A Member expression.
#' @param level A Level expression.
#' @return MDX string returning Set.
#' @family member-navigation
#' @export
mdx_ancestors <- function(member, level) {
  paste0("Ancestors(", member, ", ", level, ")")
}

#' MDX Ascendants function
#'
#' Returns the set of the ascendants of a specified member.
#'
#' @param member A Member expression.
#' @return MDX string returning Set.
#' @family member-navigation
#' @export
mdx_ascendants <- function(member) {
  paste0("Ascendants(", member, ")")
}

#' MDX CalculatedChild function
#'
#' Returns an existing calculated child member with name <String> from the specified <Member>.
#'
#' @param member A Member expression.
#' @param string A String expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_calculated_child <- function(member, string) {
  args <- ""
  args <- if (nchar(args) > 0) paste0(args, ", ", string) else string
  paste0(member, ".CalculatedChild(", args, ")")
}

#' MDX Children function
#'
#' Returns the children of a member.
#'
#' @param member A Member expression.
#' @return MDX string returning Set.
#' @family member-navigation
#' @export
mdx_children <- function(member) {
  paste0(member, ".Children")
}

#' MDX Cousin function
#'
#' Returns the member with the same relative position under <ancestor member> as the member specified.
#'
#' @param member1 A Member expression.
#' @param member2 A Member expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_cousin <- function(member1, member2) {
  paste0("Cousin(", member1, ", ", member2, ")")
}

#' MDX CurrentMember function
#'
#' Returns the current member along a hierarchy during an iteration.
#'
#' @param hierarchy A Hierarchy expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_hierarchy_current_member <- function(hierarchy) {
  paste0(hierarchy, ".CurrentMember")
}

#' MDX DataMember function
#'
#' Returns the system-generated data member that is associated with a nonleaf member of a dimension.
#'
#' @param member A Member expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_data_member <- function(member) {
  paste0(member, ".DataMember")
}

#' MDX DefaultMember function
#'
#' Returns the default member of a hierarchy.
#'
#' @param hierarchy A Hierarchy expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_hierarchy_default_member <- function(hierarchy) {
  paste0(hierarchy, ".DefaultMember")
}

#' MDX Descendants function
#'
#' Returns the set of descendants of a member at a specified level, optionally including or excluding descendants in other levels.
#'
#' @param member A Member expression.
#' @param level A Level expression (optional).
#' @param desc_flag SELF, AFTER, BEFORE, BEFORE_AND_AFTER, SELF_AND_AFTER, SELF_AND_BEFORE, SELF_BEFORE_AFTER, LEAVES.
#' @return MDX string returning Set.
#' @family member-navigation
#' @export
mdx_descendants <- function(member, level = NULL, desc_flag = NULL) {
  args <- paste0(member)
  if (!is.null(level)) args <- paste0(args, ", ", level)
  if (!is.null(desc_flag)) args <- paste0(args, ", ", desc_flag)
  paste0("Descendants(", args, ")")
}

#' MDX FirstChild function
#'
#' Returns the first child of a member.
#'
#' @param member A Member expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_first_child <- function(member) {
  paste0(member, ".FirstChild")
}

#' MDX FirstSibling function
#'
#' Returns the first child of the parent of a member.
#'
#' @param member A Member expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_first_sibling <- function(member) {
  paste0(member, ".FirstSibling")
}

#' MDX Lag function
#'
#' Returns a member further along the specified member's dimension.
#'
#' @param member A Member expression.
#' @param numeric_expr A Numeric Expression expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_lag <- function(member, numeric_expr) {
  args <- ""
  args <- if (nchar(args) > 0) paste0(args, ", ", numeric_expr) else numeric_expr
  paste0(member, ".Lag(", args, ")")
}

#' MDX LastChild function
#'
#' Returns the last child of a member.
#'
#' @param member A Member expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_last_child <- function(member) {
  paste0(member, ".LastChild")
}

#' MDX LastSibling function
#'
#' Returns the last child of the parent of a member.
#'
#' @param member A Member expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_last_sibling <- function(member) {
  paste0(member, ".LastSibling")
}

#' MDX Lead function
#'
#' Returns a member further along the specified member's dimension.
#'
#' @param member A Member expression.
#' @param numeric_expr A Numeric Expression expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_lead <- function(member, numeric_expr) {
  args <- ""
  args <- if (nchar(args) > 0) paste0(args, ", ", numeric_expr) else numeric_expr
  paste0(member, ".Lead(", args, ")")
}

#' MDX NextMember function
#'
#' Returns the next member in the level that contains a specified member.
#'
#' @param member A Member expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_next_member <- function(member) {
  paste0(member, ".NextMember")
}

#' MDX Parent function
#'
#' Returns the parent of a member.
#'
#' @param member A Member expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_parent <- function(member) {
  paste0(member, ".Parent")
}

#' MDX PrevMember function
#'
#' Returns the previous member in the level that contains a specified member.
#'
#' @param member A Member expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_prev_member <- function(member) {
  paste0(member, ".PrevMember")
}

#' MDX Siblings function
#'
#' Returns the siblings of a specified member, including the member itself.
#'
#' @param member A Member expression.
#' @return MDX string returning Set.
#' @family member-navigation
#' @export
mdx_siblings <- function(member) {
  paste0(member, ".Siblings")
}

#' MDX StrToMember function
#'
#' Returns a member from a unique name String in MDX format.
#'
#' @param string A String expression.
#' @return MDX string returning Member.
#' @family member-navigation
#' @export
mdx_str_to_member <- function(string) {
  paste0("StrToMember(", string, ")")
}

#' MDX ValidMeasure function
#'
#' Returns a valid measure in a virtual cube by forcing inapplicable dimensions to their top level.
#'
#' @param tuple A Tuple expression.
#' @return MDX string returning Numeric Expression.
#' @family member-navigation
#' @export
mdx_valid_measure <- function(tuple) {
  paste0("ValidMeasure(", tuple, ")")
}

