#' @title MDX Statistical Functions (auto-generated)
#' @description Auto-generated MDX function wrappers for statistical.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX Correlation function
#'
#' Returns the correlation of two series evaluated over a set.
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression.
#' @param numeric_expr_3 A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family statistical
#' @export
mdx_correlation <- function(set_expr, numeric_expr, numeric_expr_3 = NULL) {
  args <- paste0(set_expr, ", ", numeric_expr)
  if (!is.null(numeric_expr_3)) args <- paste0(args, ", ", numeric_expr_3)
  paste0("Correlation(", args, ")")
}

#' MDX Covariance function
#'
#' Returns the covariance of two series evaluated over a set (biased).
#'
#' @param set_expr A Set expression.
#' @param numeric_expression1 A Numeric Expression expression.
#' @param numeric_expression2 A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family statistical
#' @export
mdx_covariance <- function(set_expr, numeric_expression1, numeric_expression2 = NULL) {
  args <- paste0(set_expr, ", ", numeric_expression1)
  if (!is.null(numeric_expression2)) args <- paste0(args, ", ", numeric_expression2)
  paste0("Covariance(", args, ")")
}

#' MDX LinRegIntercept function
#'
#' Calculates the linear regression of a set and returns the value of b in the regression line y = ax + b.
#'
#' @param set_expr A Set expression.
#' @param numeric_y A Numeric Expression expression.
#' @param numeric_x A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family statistical
#' @export
mdx_lin_reg_intercept <- function(set_expr, numeric_y, numeric_x = NULL) {
  args <- paste0(set_expr, ", ", numeric_y)
  if (!is.null(numeric_x)) args <- paste0(args, ", ", numeric_x)
  paste0("LinRegIntercept(", args, ")")
}

#' MDX LinRegPoint function
#'
#' Calculates the linear regression of a set and returns the value of y in the regression line y = ax + b.
#'
#' @param x_point A Numeric Expression expression.
#' @param set_expr A Set expression.
#' @param y A Numeric Expression expression.
#' @param x A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family statistical
#' @export
mdx_lin_reg_point <- function(x_point, set_expr, y, x = NULL) {
  args <- paste0(x_point, ", ", set_expr, ", ", y)
  if (!is.null(x)) args <- paste0(args, ", ", x)
  paste0("LinRegPoint(", args, ")")
}

#' MDX LinRegR2 function
#'
#' Calculates the linear regression of a set and returns R2 (the coefficient of determination).
#'
#' @param set_expr A Set expression.
#' @param y A Numeric Expression expression.
#' @param x A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family statistical
#' @export
mdx_lin_reg_r2 <- function(set_expr, y, x = NULL) {
  args <- paste0(set_expr, ", ", y)
  if (!is.null(x)) args <- paste0(args, ", ", x)
  paste0("LinRegR2(", args, ")")
}

#' MDX LinRegSlope function
#'
#' Calculates the linear regression of a set and returns the value of a in the regression line y = ax + b.
#'
#' @param set_expr A Set expression.
#' @param y A Numeric Expression expression.
#' @param x A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family statistical
#' @export
mdx_lin_reg_slope <- function(set_expr, y, x = NULL) {
  args <- paste0(set_expr, ", ", y)
  if (!is.null(x)) args <- paste0(args, ", ", x)
  paste0("LinRegSlope(", args, ")")
}

#' MDX LinRegVariance function
#'
#' Calculates the linear regression of a set and returns the variance associated with the regression line y = ax + b.
#'
#' @param set_expr A Set expression.
#' @param y A Numeric Expression expression.
#' @param x A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family statistical
#' @export
mdx_lin_reg_variance <- function(set_expr, y, x = NULL) {
  args <- paste0(set_expr, ", ", y)
  if (!is.null(x)) args <- paste0(args, ", ", x)
  paste0("LinRegVariance(", args, ")")
}

#' MDX Percentile function
#'
#' Returns the value of the tuple that is at a given percentile of a set.
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression.
#' @param numeric_expr_3 A Numeric Expression expression.
#' @return MDX string returning Numeric Expression.
#' @family statistical
#' @export
mdx_percentile <- function(set_expr, numeric_expr, numeric_expr_3) {
  paste0("Percentile(", set_expr, ", ", numeric_expr, ", ", numeric_expr_3, ")")
}

#' MDX Stdev function
#'
#' Returns the standard deviation of a numeric expression evaluated over a set (unbiased).
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family statistical
#' @export
mdx_stdev <- function(set_expr, numeric_expr = NULL) {
  args <- paste0(set_expr)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("Stdev(", args, ")")
}

#' MDX StdevP function
#'
#' Returns the standard deviation of a numeric expression evaluated over a set (biased).
#'
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family statistical
#' @export
mdx_stdev_p <- function(set_expr, numeric_expr = NULL) {
  args <- paste0(set_expr)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("StdevP(", args, ")")
}

#' MDX Var function
#'
#' Returns the variance of a numeric expression evaluated over a set (unbiased).
#'
#' @param set_expr A Set expression.
#' @param value A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family statistical
#' @export
mdx_var <- function(set_expr, value = NULL) {
  args <- paste0(set_expr)
  if (!is.null(value)) args <- paste0(args, ", ", value)
  paste0("Var(", args, ")")
}

#' MDX VarP function
#'
#' Returns the variance of a numeric expression evaluated over a set (biased).
#'
#' @param set_expr A Set expression.
#' @param value A Numeric Expression expression (optional).
#' @return MDX string returning Numeric Expression.
#' @family statistical
#' @export
mdx_var_p <- function(set_expr, value = NULL) {
  args <- paste0(set_expr)
  if (!is.null(value)) args <- paste0(args, ", ", value)
  paste0("VarP(", args, ")")
}

