#' @title MDX Ranking Functions (auto-generated)
#' @description Auto-generated MDX function wrappers for ranking.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX BottomCount function
#'
#' Returns a specified number of items from the bottom of a set, optionally ordering the set first.
#'
#' @param set_expr A Set expression.
#' @param count A Numeric Expression expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Set.
#' @family ranking
#' @export
mdx_bottom_count <- function(set_expr, count, numeric_expr = NULL) {
  args <- paste0(set_expr, ", ", count)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("BottomCount(", args, ")")
}

#' MDX BottomPercent function
#'
#' Sorts a set and returns the bottom N elements whose cumulative total is at least a specified percentage.
#'
#' @param set_expr A Set expression.
#' @param percentage A Numeric Expression expression.
#' @param numeric_expr A Numeric Expression expression.
#' @return MDX string returning Set.
#' @family ranking
#' @export
mdx_bottom_percent <- function(set_expr, percentage, numeric_expr) {
  paste0("BottomPercent(", set_expr, ", ", percentage, ", ", numeric_expr, ")")
}

#' MDX BottomSum function
#'
#' Sorts a set and returns the bottom N elements whose cumulative total is at least a specified value.
#'
#' @param set_expr A Set expression.
#' @param value A Numeric Expression expression.
#' @param numeric_expr A Numeric Expression expression.
#' @return MDX string returning Set.
#' @family ranking
#' @export
mdx_bottom_sum <- function(set_expr, value, numeric_expr) {
  paste0("BottomSum(", set_expr, ", ", value, ", ", numeric_expr, ")")
}

#' MDX Rank function
#'
#' Returns the one-based rank of a tuple in a set.
#'
#' @param tuple A Tuple expression.
#' @param set_expr A Set expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Integer.
#' @family ranking
#' @export
mdx_rank <- function(tuple, set_expr, numeric_expr = NULL) {
  args <- paste0(tuple, ", ", set_expr)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("Rank(", args, ")")
}

#' MDX TopCount function
#'
#' Returns a specified number of items from the top of a set, optionally ordering the set first.
#'
#' @param set_expr A Set expression.
#' @param count A Numeric Expression expression.
#' @param numeric_expr A Numeric Expression expression (optional).
#' @return MDX string returning Set.
#' @family ranking
#' @export
mdx_top_count <- function(set_expr, count, numeric_expr = NULL) {
  args <- paste0(set_expr, ", ", count)
  if (!is.null(numeric_expr)) args <- paste0(args, ", ", numeric_expr)
  paste0("TopCount(", args, ")")
}

#' MDX TopPercent function
#'
#' Sorts a set and returns the top N elements whose cumulative total is at least a specified percentage.
#'
#' @param set_expr A Set expression.
#' @param percentage A Numeric Expression expression.
#' @param numeric_expr A Numeric Expression expression.
#' @return MDX string returning Set.
#' @family ranking
#' @export
mdx_top_percent <- function(set_expr, percentage, numeric_expr) {
  paste0("TopPercent(", set_expr, ", ", percentage, ", ", numeric_expr, ")")
}

#' MDX TopSum function
#'
#' Sorts a set and returns the top N elements whose cumulative total is at least a specified value.
#'
#' @param set_expr A Set expression.
#' @param value A Numeric Expression expression.
#' @param numeric_expr A Numeric Expression expression.
#' @return MDX string returning Set.
#' @family ranking
#' @export
mdx_top_sum <- function(set_expr, value, numeric_expr) {
  paste0("TopSum(", set_expr, ", ", value, ", ", numeric_expr, ")")
}

