#' @title MDX User-Defined Functions (auto-generated)
#' @description Auto-generated MDX function wrappers for udf.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX CurrentDateMember function
#'
#' Returns the closest or exact member within the specified dimension corresponding to the current date, in the format specified by the format parameter. Format strings are the same as used by the MDX Format function, namely the Visual Basic format strings. See http://www.apostate.com/programming/vb-format.html.
#'
#' @param hierarchy A Hierarchy expression.
#' @param format A String expression.
#' @param match_type A Symbol expression (optional).
#' @return MDX string returning Member.
#' @family udf
#' @export
mdx_current_date_member <- function(hierarchy, format, match_type = NULL) {
  args <- paste0(hierarchy, ", ", format)
  if (!is.null(match_type)) args <- paste0(args, ", ", match_type)
  paste0("CurrentDateMember(", args, ")")
}

#' MDX CurrentDateString function
#'
#' Returns the current date formatted as specified by the format parameter.
#'
#' @param format A String expression.
#' @return MDX string returning String.
#' @family udf
#' @export
mdx_current_date_string <- function(format) {
  paste0("CurrentDateString(", format, ")")
}

#' MDX LastNonEmpty function
#'
#' Returns the last member of a set whose value is not empty
#'
#' @param set_expr A Set expression.
#' @param member A Member expression.
#' @return MDX string returning Member.
#' @family udf
#' @export
mdx_last_non_empty <- function(set_expr, member) {
  paste0("LastNonEmpty(", set_expr, ", ", member, ")")
}

#' MDX NullValue function
#'
#' Returns the null value
#'
#' @return MDX string returning Numeric Expression.
#' @family udf
#' @export
mdx_null_value <- function() {
  paste0("NullValue()")
}

