#' @title MDX Set Construction Functions (auto-generated)
#' @description Auto-generated MDX function wrappers for set-construction.
#' DO NOT EDIT - this file is generated by FunctionMetaDataExportTest.

#' MDX AddCalculatedMembers function
#'
#' Adds calculated members to a set.
#'
#' @param set_expr A Set expression.
#' @return MDX string returning Set.
#' @family set-construction
#' @export
mdx_add_calculated_members <- function(set_expr) {
  paste0("AddCalculatedMembers(", set_expr, ")")
}

#' MDX Head function
#'
#' Returns the first specified number of elements in a set.
#'
#' @param set_expr A Set expression.
#' @param numeric_expression A Numeric Expression expression (optional).
#' @return MDX string returning Set.
#' @family set-construction
#' @export
mdx_head <- function(set_expr, numeric_expression = NULL) {
  args <- paste0(set_expr)
  if (!is.null(numeric_expression)) args <- paste0(args, ", ", numeric_expression)
  paste0("Head(", args, ")")
}

#' MDX Item function
#'
#' Returns a member from the tuple specified in <Tuple>. The member to be returned is specified by the zero-based position of the member in the set in <Index>.
#'
#' @param tuple A Tuple expression.
#' @param index A Numeric Expression expression.
#' @return MDX string returning Member.
#' @family set-construction
#' @export
mdx_item <- function(tuple, index) {
  args <- ""
  args <- if (nchar(args) > 0) paste0(args, ", ", index) else index
  paste0(tuple, ".Item(", args, ")")
}

#' MDX SetToStr function
#'
#' Constructs a string from a set.
#'
#' @param set_expr A Set expression.
#' @return MDX string returning String.
#' @family set-construction
#' @export
mdx_set_to_str <- function(set_expr) {
  paste0("SetToStr(", set_expr, ")")
}

#' MDX StripCalculatedMembers function
#'
#' Removes calculated members from a set.
#'
#' @param set_expr A Set expression.
#' @return MDX string returning Set.
#' @family set-construction
#' @export
mdx_strip_calculated_members <- function(set_expr) {
  paste0("StripCalculatedMembers(", set_expr, ")")
}

#' MDX Subset function
#'
#' Returns a subset of elements from a set.
#'
#' @param set_expr A Set expression.
#' @param start A Numeric Expression expression.
#' @param count A Numeric Expression expression (optional).
#' @return MDX string returning Set.
#' @family set-construction
#' @export
mdx_subset <- function(set_expr, start, count = NULL) {
  args <- paste0(set_expr, ", ", start)
  if (!is.null(count)) args <- paste0(args, ", ", count)
  paste0("Subset(", args, ")")
}

#' MDX Tail function
#'
#' Returns a subset from the end of a set.
#'
#' @param set_expr A Set expression.
#' @param count A Numeric Expression expression (optional).
#' @return MDX string returning Set.
#' @family set-construction
#' @export
mdx_tail <- function(set_expr, count = NULL) {
  args <- paste0(set_expr)
  if (!is.null(count)) args <- paste0(args, ", ", count)
  paste0("Tail(", args, ")")
}

